version: 1.0.{build}
init:
  - git config --global core.autocrlf input
configuration: Release
image: Visual Studio 2017
build:
  project: mo-gen.sln
  publish_nuget: true
  publish_nuget_symbols: true
after_build:
  pwsh: dotnet pack src/mo-gen/mo-gen.csproj
artifacts:
  - path: "**/*.nupkg"
    name: NuGetPackages
install:
  - dotnet restore
deploy:
- provider: NuGet
  api_key:
    secure: F67S4wlZEdRiowy0DR25bnfszCdcNsO3R6ykHeGTWEsl6iqXUJEx+W4M6tk6+iVP
  on:
    APPVEYOR_REPO_TAG: true
    branch: master
  artifact: NuGetPackages
- provider: GitHub
  auth_token:
    secure: MFZg3Ryx8cZ9XWIf8qvSE+48pmQc2LPAcPiRQ7bUtPRKj4mXvn+mtZVzPV7tQyX1
  on:
    APPVEYOR_REPO_TAG: true
    branch: master
  artifact: NuGetPackages
  prerelease: false
  draft: true